---
# pve-network: IPv6 tasks
# Enable or disable IPv6

- name: Configure IPv6 via sysctl
  ansible.builtin.sysctl:
    name: "{{ item }}"
    value: "{{ '0' if pve_ipv6_enabled else '1' }}"
    sysctl_file: /etc/sysctl.d/99-ipv6.conf
    reload: true
    state: present
  loop:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Display IPv6 status
  ansible.builtin.debug:
    msg: "IPv6 is now {{ 'enabled' if pve_ipv6_enabled else 'disabled' }}"
